spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_ENDPOINT}:${LOCAL_DB_PORT}/auth_system_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: ${JWT_SECRET_KEY}
    #    만료 시간 단위는 밀리초(ms) 단위
    #    600000 = 10분
    #    864000000 = 24시간
    access_expiry: 600000
    refresh_expiry: 600000

  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PWD}